# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XingAll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('xing', models.CharField(max_length=32, verbose_name='姓氏')),
                ('num', models.CharField(max_length=32, verbose_name='数量')),
            ],
            options={
                'db_table': 'xingall',
            },
        ),
    ]
